Repository City-of-Helsinki/linkedevents-ui, pull requests merged in 2018-06, with the labels that each got.

#324 [Fix] Fix broken Webpack HMR when navigating to subroute returning 404
  .eslintignore
  config/webpack/common.js
  config/webpack/dev.js
  config/webpack/prod.js
  server/index.js
  server/renderIndexTemplate.js
  server/server.js
  src/index.jade
Labels: enhancement

#330 [Enhancement/Fix] Refactor some ref usage (deprecated), fix React.createClass warning, upgrade react-bootstrap
  .eslintrc
  .gitignore
  package.json
  src/components/FilterableEventTable/index.js
  src/components/FormFields/index.js
  src/components/HelFormFields/HelAutoComplete.js
  src/components/HelFormFields/HelCheckbox.js
  src/components/HelFormFields/HelDatePicker.js
  src/components/HelFormFields/HelDateTimeField.js
  src/components/HelFormFields/HelLabeledCheckboxGroup.js
  src/components/HelFormFields/HelLanguageSelect.js
  src/components/HelFormFields/HelOffersField.js
  src/components/HelFormFields/HelTextField.js
  src/components/HelFormFields/MultiLanguageField.js
  src/components/HelFormFields/NewOffer.js
  src/components/ImageEdit/index.js
  src/components/ImagePicker/index.js
  src/components/ImageThumbnail/index.js
  src/components/RecurringEvent/RecurringDateRangePicker.js
  src/components/RecurringEvent/index.js
  src/components/SearchBar/index.js
  src/components/ValidationPopover/index.js
  src/i18n/en.json
  src/i18n/fi.json
  src/index.js
  src/validation/validationRules.js
  src/views/App/index.js
  src/views/Editor/index.js
  src/views/Event/index.js
  src/views/EventCreated/index.js
  src/views/Notification/index.js
  yarn.lock
Labels: enhancement

#332 [Fix] Make language selection checkboxes align neatly
  src/assets/main.scss
  src/components/FormFields/index.js
  src/components/HelFormFields/HelCheckbox.scss
  src/components/HelFormFields/HelLanguageSelect.js
  src/components/HelFormFields/HelOffersField.js
  src/components/HelFormFields/HelOffersField.scss
  src/views/Editor/index.scss
Labels: bug

#335 [Fix] Image Upload Modal didn't work due to event container bouncing to child element
  src/components/ImagePicker/index.js
Labels: bug

#333 [Feature] Add counter to location_extra_info field
  src/actions/editor.js
  src/components/FormFields/index.js
  src/components/HelFormFields/HelDateTimeField.js
  src/components/HelFormFields/HelTextField.js
  src/components/HelFormFields/HelTimePicker.js
  src/components/HelFormFields/MultiLanguageField.js
  src/components/HelFormFields/NewOffer.js
  src/components/ImageEdit/index.js
  src/components/RecurringEvent/RecurringDateRangePicker.js
  src/components/RecurringEvent/index.js
  src/components/SearchBar/index.js
  src/components/ValidationPopover/index.js
  src/constants.js
  src/i18n/fi.json
  src/utils/helpers.js
  src/validation/validationRules.js
  src/validation/validator.js
Labels: enhancement

#328 [Feature] Update styling for toolbar linked courses
  src/assets/_colors.scss
  src/assets/_fonts.scss
  src/assets/images/helsinki-logo.svg
  src/assets/main.scss
  src/components/Header/index.js
  src/components/Header/index.scss
  src/i18n/en.json
  src/i18n/fi.json
  src/themes/hel/index.js
  src/views/Help/index.js
  src/views/Search/index.js
  yarn.lock
Labels: Link Courses UI, enhancement, in progress

#337 [Feature] Create language selector box for LinkedEvent (+ LinkCourses)
  src/actions/userLocale.js
  src/actors/validator.js
  src/components/EventDetails/index.js
  src/components/EventDetails/index.scss
  src/components/EventGrid/index.js
  src/components/EventGrid/index.scss
  src/components/FilterableEventTable/index.js
  src/components/FilterableEventTable/index.scss
  src/components/FormFields/index.js
  src/components/Header/index.js
  src/components/Header/index.scss
  src/components/HelFormFields/HelAutoComplete.js
  src/components/HelFormFields/HelDatePicker.js
  src/components/HelFormFields/HelLanguageSelect.js
  src/components/ImageGalleryGrid/index.js
  src/components/ImageThumbnail/index.js
  src/components/IntlProviderWrapper/index.js
  src/components/SearchBar/index.js
  src/constants.js
  src/i18n/en.json
  src/i18n/fi.json
  src/index.js
  src/reducers/index.js
  src/reducers/userLocale.js
  src/views/App/index.js
  src/views/Editor/index.js
  src/views/Event/index.js
  src/views/Event/index.scss
  src/views/Notification/index.js
Labels: enhancement
